# Generated by Django 3.1 on 2020-09-16 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='core.tag'),
            preserve_default=False,
        ),
    ]
