# Generated by Django 3.1 on 2020-09-17 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.tag'),
        ),
    ]
