# Generated by Django 3.1 on 2020-09-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200918_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='created_data',
            new_name='created',
        ),
    ]
