# Generated by Django 3.1 on 2020-09-27 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200918_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.tag'),
        ),
    ]
